---
name: Code build and review
on: push
branches:
  - master
  - dev
  - test
jobs:
  buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the current repository on the runner
        uses: actions/checkout@v4
      - name: Setup Java 17 and maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - name: Build the code
        run: mvn package
